version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: SalesApiDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - project-network

  gateway:
    build:
      context: .
      dockerfile: src/SalesApi.Gateway/Dockerfile
    container_name: ocelot-gateway
    ports:
      - "7777:7777"
    environment:
      - ASPNETCORE_URLS=http://+:7777
    depends_on:
      - sales-api
    networks:
      - project-network

  sales-api:
    build:
      context: .
      dockerfile: src/SalesApi/Dockerfile
    container_name: sales-api
    ports:
      - "8090:8090"
    environment:
      - ConnectionStrings__SalesApiDb=Host=db;Database=SalesApiDb;Username=postgres;Password=admin
    depends_on:
      - db
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
